// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArKaFIdzJEC6TAShZG89eNYNKrTHX9lG0',
    appId: '1:320319839450:web:5a7b9859e460858468d9e3',
    messagingSenderId: '320319839450',
    projectId: 'khadmaty-71e8b',
    authDomain: 'khadmaty-71e8b.firebaseapp.com',
    storageBucket: 'khadmaty-71e8b.appspot.com',
    measurementId: 'G-T0C0C4TJTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9yC2ngXWPLWkixP2d9V5B6unwFzLcaw0',
    appId: '1:320319839450:android:e27c11ce19b144b068d9e3',
    messagingSenderId: '320319839450',
    projectId: 'khadmaty-71e8b',
    storageBucket: 'khadmaty-71e8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyrsnfAFclE7mMptZq1S4dzpumj_RUnQs',
    appId: '1:320319839450:ios:f4b2af4718d696b368d9e3',
    messagingSenderId: '320319839450',
    projectId: 'khadmaty-71e8b',
    storageBucket: 'khadmaty-71e8b.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyrsnfAFclE7mMptZq1S4dzpumj_RUnQs',
    appId: '1:320319839450:ios:b09268ca248f7ecc68d9e3',
    messagingSenderId: '320319839450',
    projectId: 'khadmaty-71e8b',
    storageBucket: 'khadmaty-71e8b.appspot.com',
    iosBundleId: 'com.example.graduationProject.RunnerTests',
  );
}
